[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "prompteval"
version = "0.1.0"
description = ""
authors = [{name="PromptEval Team", email="felipemaiapolo@gmail.com"}]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "datasets==2.19.2",
    "huggingface-hub==0.23.2",
    "multiprocess==0.70.16",
    "numpy>=1.25.2",
    "packaging==24.0",
    "pandas==2.2.2",
    "pillow==10.3.0",
    "pyarrow==16.1.0",
    "PyYAML==6.0.1",
    "regex==2024.5.15",
    "requests==2.32.3",
    "safetensors==0.4.3",
    "scikit-learn>=1.5.0",
    "scipy==1.13.1",
    "sentence-transformers==3.0.0",
    "sympy==1.12.1",
    "tokenizers==0.19.1",
    "torch==2.3.0",
    "tdqm>=0.0.1",
    "transformers==4.41.2",
    "matplotlib>=3.7.3",
]

[project.optional-dependencies]
dev = [
    "black>=23.9.1",
    "flake8>=6.1.0",
    "isort>=5.12.0",
    "setuptools_scm>=8.0.1",
    "tdqm>=0.0.1",
    "pre-commit>=3.6.2",
]

[tool.setuptools.packages.find]
include = ["prompteval*"]

[tool.setuptools_scm]
write_to = "src/_version.py"
write_to_template = '__version__ = "{version}"\n'
